baseURL = 'https://evoleinik.com/'
languageCode = 'en-us'
title = 'Eugene Oleinik'
theme = 'PaperMod'

[params]
author = 'Eugene Oleinik'
description = 'Building things that work.'
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
showBreadCrumbs = false
showCodeCopyButtons = true
defaultTheme = 'auto'

  [params.homeInfoParams]
  Title = 'Eugene Oleinik'
  Content = 'Building things that work.'

  [[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/evoleinik'

  [[params.socialIcons]]
  name = 'linkedin'
  url = 'https://linkedin.com/in/evoleinik'

  [[params.socialIcons]]
  name = 'email'
  url = 'mailto:ev@evoleinik.com'

[menu]
  [[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 10

  [[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 20

[outputs]
home = ['HTML', 'RSS', 'LLMS', 'LLMSFULL']

[outputFormats]
  [outputFormats.LLMS]
  baseName = 'llms'
  isPlainText = true
  mediaType = 'text/plain'
  notAlternative = true

  [outputFormats.LLMSFULL]
  baseName = 'llms-full'
  isPlainText = true
  mediaType = 'text/plain'
  notAlternative = true

[markup]
  [markup.highlight]
  style = 'monokai'
